// flow-typed signature: d60482498c37d9853e645218428d7abe
// flow-typed version: <<STUB>>/babel-plugin-transform-flow-strip-types_vhttps://registry.npmjs.org/babel-plugin-transform-flow-strip-types/-/babel-plugin-transform-flow-strip-types-6.22.0.tgz/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-flow-strip-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-flow-strip-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-flow-strip-types/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-flow-strip-types/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-flow-strip-types/lib/index'>;
}
