// flow-typed signature: 22443b42c4fd8e2bd932a7ec817880e0
// flow-typed version: <<STUB>>/bcrypt-nodejs_v0.0.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bcrypt-nodejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bcrypt-nodejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bcrypt-nodejs/bCrypt' {
  declare module.exports: any;
}

declare module 'bcrypt-nodejs/test-async' {
  declare module.exports: any;
}

declare module 'bcrypt-nodejs/test-sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bcrypt-nodejs/bCrypt.js' {
  declare module.exports: $Exports<'bcrypt-nodejs/bCrypt'>;
}
declare module 'bcrypt-nodejs/test-async.js' {
  declare module.exports: $Exports<'bcrypt-nodejs/test-async'>;
}
declare module 'bcrypt-nodejs/test-sync.js' {
  declare module.exports: $Exports<'bcrypt-nodejs/test-sync'>;
}
