// flow-typed signature: c2dc7fa49282c266f9383b5feb83967c
// flow-typed version: <<STUB>>/neoform_v^0.2.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'neoform'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'neoform' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'neoform/dist/neoform' {
  declare module.exports: any;
}

declare module 'neoform/dist/neoform.min' {
  declare module.exports: any;
}

declare module 'neoform/es/Field' {
  declare module.exports: any;
}

declare module 'neoform/es/Form' {
  declare module.exports: any;
}

declare module 'neoform/es/index' {
  declare module.exports: any;
}

declare module 'neoform/lib/Field' {
  declare module.exports: any;
}

declare module 'neoform/lib/Form' {
  declare module.exports: any;
}

declare module 'neoform/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'neoform/dist/neoform.js' {
  declare module.exports: $Exports<'neoform/dist/neoform'>;
}
declare module 'neoform/dist/neoform.min.js' {
  declare module.exports: $Exports<'neoform/dist/neoform.min'>;
}
declare module 'neoform/es/Field.js' {
  declare module.exports: $Exports<'neoform/es/Field'>;
}
declare module 'neoform/es/Form.js' {
  declare module.exports: $Exports<'neoform/es/Form'>;
}
declare module 'neoform/es/index.js' {
  declare module.exports: $Exports<'neoform/es/index'>;
}
declare module 'neoform/lib/Field.js' {
  declare module.exports: $Exports<'neoform/lib/Field'>;
}
declare module 'neoform/lib/Form.js' {
  declare module.exports: $Exports<'neoform/lib/Form'>;
}
declare module 'neoform/lib/index.js' {
  declare module.exports: $Exports<'neoform/lib/index'>;
}
