// flow-typed signature: 7504e5de88cc55142096aebc7a84d8f1
// flow-typed version: <<STUB>>/neoform-plain-object-helpers_v^0.1.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'neoform-plain-object-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'neoform-plain-object-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'neoform-plain-object-helpers/dist/neoform-plain-object-helpers' {
  declare module.exports: any;
}

declare module 'neoform-plain-object-helpers/dist/neoform-plain-object-helpers.min' {
  declare module.exports: any;
}

declare module 'neoform-plain-object-helpers/es/index' {
  declare module.exports: any;
}

declare module 'neoform-plain-object-helpers/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'neoform-plain-object-helpers/dist/neoform-plain-object-helpers.js' {
  declare module.exports: $Exports<'neoform-plain-object-helpers/dist/neoform-plain-object-helpers'>;
}
declare module 'neoform-plain-object-helpers/dist/neoform-plain-object-helpers.min.js' {
  declare module.exports: $Exports<'neoform-plain-object-helpers/dist/neoform-plain-object-helpers.min'>;
}
declare module 'neoform-plain-object-helpers/es/index.js' {
  declare module.exports: $Exports<'neoform-plain-object-helpers/es/index'>;
}
declare module 'neoform-plain-object-helpers/lib/index.js' {
  declare module.exports: $Exports<'neoform-plain-object-helpers/lib/index'>;
}
