// flow-typed signature: 2f2d9a6e759130fb62d58ecdc0060a7c
// flow-typed version: <<STUB>>/neoform-validation_v^0.3.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'neoform-validation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'neoform-validation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'neoform-validation/dist/neoform-validation' {
  declare module.exports: any;
}

declare module 'neoform-validation/dist/neoform-validation.min' {
  declare module.exports: any;
}

declare module 'neoform-validation/es/Field' {
  declare module.exports: any;
}

declare module 'neoform-validation/es/Form' {
  declare module.exports: any;
}

declare module 'neoform-validation/es/index' {
  declare module.exports: any;
}

declare module 'neoform-validation/lib/Field' {
  declare module.exports: any;
}

declare module 'neoform-validation/lib/Form' {
  declare module.exports: any;
}

declare module 'neoform-validation/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'neoform-validation/dist/neoform-validation.js' {
  declare module.exports: $Exports<'neoform-validation/dist/neoform-validation'>;
}
declare module 'neoform-validation/dist/neoform-validation.min.js' {
  declare module.exports: $Exports<'neoform-validation/dist/neoform-validation.min'>;
}
declare module 'neoform-validation/es/Field.js' {
  declare module.exports: $Exports<'neoform-validation/es/Field'>;
}
declare module 'neoform-validation/es/Form.js' {
  declare module.exports: $Exports<'neoform-validation/es/Form'>;
}
declare module 'neoform-validation/es/index.js' {
  declare module.exports: $Exports<'neoform-validation/es/index'>;
}
declare module 'neoform-validation/lib/Field.js' {
  declare module.exports: $Exports<'neoform-validation/lib/Field'>;
}
declare module 'neoform-validation/lib/Form.js' {
  declare module.exports: $Exports<'neoform-validation/lib/Form'>;
}
declare module 'neoform-validation/lib/index.js' {
  declare module.exports: $Exports<'neoform-validation/lib/index'>;
}
