// flow-typed signature: e498b23fa8d8fc8a447fc0dc45e12fb0
// flow-typed version: <<STUB>>/nodemailer-ses-transport_v^1.5.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodemailer-ses-transport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodemailer-ses-transport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodemailer-ses-transport/Gruntfile' {
  declare module.exports: any;
}

declare module 'nodemailer-ses-transport/lib/ses-transport' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodemailer-ses-transport/Gruntfile.js' {
  declare module.exports: $Exports<'nodemailer-ses-transport/Gruntfile'>;
}
declare module 'nodemailer-ses-transport/lib/ses-transport.js' {
  declare module.exports: $Exports<'nodemailer-ses-transport/lib/ses-transport'>;
}
