// flow-typed signature: a7b4dde3ff5465a0dbdc020ec4304823
// flow-typed version: <<STUB>>/quoted-printable_v^1.0.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'quoted-printable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'quoted-printable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'quoted-printable/quoted-printable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'quoted-printable/quoted-printable.js' {
  declare module.exports: $Exports<'quoted-printable/quoted-printable'>;
}
