// flow-typed signature: cc995509fbcba91232a4f2b69b8937c9
// flow-typed version: <<STUB>>/sequelize-encrypted_v^1.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sequelize-encrypted'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sequelize-encrypted' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sequelize-encrypted/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sequelize-encrypted/index' {
  declare module.exports: $Exports<'sequelize-encrypted'>;
}
declare module 'sequelize-encrypted/index.js' {
  declare module.exports: $Exports<'sequelize-encrypted'>;
}
declare module 'sequelize-encrypted/test/index.js' {
  declare module.exports: $Exports<'sequelize-encrypted/test/index'>;
}
