// flow-typed signature: c9238e8daf5ef3eac9de7d29075dd289
// flow-typed version: <<STUB>>/ssacl-attribute-roles_vhttps://registry.npmjs.org/ssacl-attribute-roles/-/ssacl-attribute-roles-0.0.5.tgz/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ssacl-attribute-roles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ssacl-attribute-roles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ssacl-attribute-roles/lib/index' {
  declare module.exports: any;
}

declare module 'ssacl-attribute-roles/test/get.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ssacl-attribute-roles/lib/index.js' {
  declare module.exports: $Exports<'ssacl-attribute-roles/lib/index'>;
}
declare module 'ssacl-attribute-roles/test/get.test.js' {
  declare module.exports: $Exports<'ssacl-attribute-roles/test/get.test'>;
}
