// flow-typed signature: 2044ff498c1b896ac66de922a6c3fe01
// flow-typed version: <<STUB>>/webpack-create-file-plugin_v^0.1.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-create-file-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-create-file-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-create-file-plugin/index' {
  declare module.exports: $Exports<'webpack-create-file-plugin'>;
}
declare module 'webpack-create-file-plugin/index.js' {
  declare module.exports: $Exports<'webpack-create-file-plugin'>;
}
